#!/bin/sh

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008-2016 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# https://github.com/fullstory
###

PATH=/sbin:/usr/sbin:$PATH

# set default umask
umask 0022

# this is only invoked from fll-kde-desktop, inherit its environment
NAME="fll-lxde-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
	esac
done

###
# create .config/autostart dir
###
mkdir -p "${HOME}/.config/autostart"

###
# create ~/.config/pcmanfm with wallpaper settings
###
PCMANFM_DIR="${HOME}/.config/pcmanfm"
mkdir -p "${PCMANFM_DIR}/LXDE"
if [ ! -f "${PCMANFM_DIR}/main.lxde" ]; then
    cat > "${PCMANFM_DIR}/main.lxde" << EOF
[Desktop]
show_wallpaper=1
wallpaper=${FLL_WALLPAPER}
EOF

fi
if [ ! -f "${PCMANFM_DIR}/LXDE/pcmanfm.conf" ]; then
cat > "${PCMANFM_DIR}/LXDE/pcmanfm.conf" << EOF
[config]
bm_open_method=0
su_cmd=xdg-su -c '%s'

[volume]
mount_on_startup=1
mount_removable=1
autorun=1

[desktop]
wallpaper_mode=1
wallpaper=${FLL_WALLPAPER}.png
desktop_font=Sans 12
show_wm_menu=0

EOF
fi

###
# create ~/.language file for python keyboard switcher, if not available
###
if [ ! -f "${HOME}/.language" ]; then
    cat > "${HOME}/.language" << EOF
en,de
EOF

fi

## TODO: Trash, not available yet but scheduled for 0.4
