#!/bin/sh

# Should we offer our services?
if [ -f /etc/default/fll-kde-desktop ]; then
	. /etc/default/fll-kde-desktop
fi

[ "${KDE_SERVICES_ENABLED}" = "false" ] && exit 0

# Start krandrtray
if which krandrtray >/dev/null; then
	pgrep -x krandrtray >/dev/null || krandrtray
fi

# Start network monitor
if [ -e /usr/share/services/kded/knemod.desktop ]; then
	dcop kded kded loadModule knemod >/dev/null
fi

# Start mixer
if which kmix >/dev/null; then
	# kmix already started? sound system active?
	if ! pgrep -x kmix >/dev/null && grep -q "^snd" /proc/modules; then
		# be sure that kmix just starts in tray!
		if grep -s '^Visible=' ${HOME}/.kde/share/config/kmixrc; then
			sed -i 's/^Visible=.*/Visible=false/' ${HOME}/.kde/share/config/kmixrc
		else
			echo "Visible=false" > ${HOME}/.kde/share/config/kmixrc
		fi
		
		kmix
	fi
fi
