#!/bin/sh

# Should we offer our services?
if [ -f /etc/default/fll-kde-desktop ]; then
	. /etc/default/fll-kde-desktop
fi

if [ "${KDE_SERVICES_ENABLED}" = "false" ]; then
	exit 0
fi

# Start krandrtray
if [ -x /usr/bin/krandrtray ]; then
	xrandr -q >/dev/null 2>/dev/null && krandrtray
fi

# Start mixer
if [ -x /usr/bin/kmix ]; then
	# kmix already started? sound system active?
	if ! pgrep -x kmix >/dev/null && grep -q "^snd" /proc/modules; then
		# be sure that kmix just starts in tray!
		touch ${HOME}/.kde/share/config/kmixrc
		if grep -q '^Visible=' ${HOME}/.kde/share/config/kmixrc; then
			sed -i 's/^Visible=.*/Visible=false/' ${HOME}/.kde/share/config/kmixrc
		else
			echo "Visible=false" > ${HOME}/.kde/share/config/kmixrc
		fi
		
		kmix
	fi
fi

# Start network monitor
if [ -e /usr/share/services/kded/knemod.desktop ]; then
	dcop kded kded loadModule knemod
fi

# Start kpowersave
if [ -x /usr/bin/kpowersave ]; then
	if ! pgrep -x kpowersave >/dev/null && /usr/sbin/laptop-detect 2>/dev/null; then
		# allow kpowersave to autostart (disabled by default)
		if grep -s -q '^Autostart=' ${HOME}/.kde/share/config/kpowersaverc; then
			sed -i 's/Autostart=.*/Autostart=true/' ${HOME}/.kde/share/config/kpowersaverc
		fi

		kpowersave
	fi
fi

