#!/bin/sh

# Should we offer our services?
if [ -f /etc/default/fll-kde-desktop ]; then
	. /etc/default/fll-kde-desktop
fi

[ "${KDE_SERVICES_ENABLED}" = "false" ] && exit 0

# Start krandrtray
if which krandrtray >/dev/null; then
	pgrep -x krandrtray >/dev/null || krandrtray
fi

# Start network monitor
if [ -e /usr/share/services/kded/knemod.desktop ]; then
	dcop kded kded loadModule knemod >/dev/null
fi
