#!/bin/sh

# Should we offer our services?
if [ -f /etc/default/fll-xfce-desktop ]; then
	. /etc/default/fll-xfce-desktop
fi

if [ "${XFCE_SERVICES_ENABLED}" = "false" ]; then
	exit 0
fi

# Start krandrtray
# XXX: todo?

# Start mixer
if [ -x /usr/bin/xfce4-mixer ]; then
        # xfce4-mixer already started? sound system active?
        if ! pgrep xfce4-mixer >/dev/null && grep -q "^snd" /proc/modules; then
        	if [ -f "${FLL_LIVE_USER_HOME}/.config/xfce4/panel/panels.xml" ]; then
                	sed -i  -e "/<item name=\"xfce4-mixer\"/d" \
                        	-e "s|^\([ \t]*\)\(<item[ \t]*name\=\"systray\".*\)|\1<item name=\"xfce4-mixer\" id=\"11927313170\"\/\>\n\1\2|" \
                                "${FLL_LIVE_USER_HOME}/.config/xfce4/panel/panels.xml"
                fi
	fi
fi

# Start network monitor
# XXX: todo?

# Start battmon plugin
if [ -x /usr/lib/xfce4-battery-plugin/xfce4/panel-plugins/xfce4-battery-plugin ]; then
        if ! pgrep xfce4-battery >/dev/null && pidof powersaved >/dev/null; then
        	if [ -f "${FLL_LIVE_USER_HOME}/.config/xfce4/panel/panels.xml" ]; then
                	sed -i  -e "/<item name=\"battmon\"/d" \
                        	-e "s|^\([ \t]*\)\(<item[ \t]*name\=\"systray\".*\)|\1<item name=\"battmon\" id=\"11927411720\"\/\>\n\1\2|" \
                                "${FLL_LIVE_USER_HOME}/.config/xfce4/panel/panels.xml"
                fi
        fi
fi

