#!/bin/sh

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

PATH=/sbin:/usr/sbin:$PATH

# set default umask
umask 0022

# this is only invoked from fll-kde-desktop, inherit its environment
NAME="fll-xfce-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
		nointro)
			NOINTRO="yes"
			;;
	esac
done

###
# set wallpaper and desktop defaults in desktop.xml
###
mkdir -p "${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml"
XFCE_DESKTOP_XML="${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/desktop.xml"

# handle case where FLL_WALLPAPER is defined in kde4 directory syntax
# sidux-art-wallpaper-* provides a symlink in /usr/share/wallpapers/ to common res wallpaper
if [ -d ${FLL_WALLPAPER} ]; then
	FLL_WALLPAPER=$(find $(dirname ${FLL_WALLPAPER}) -maxdepth 1 -type l -iname $(basename ${FLL_WALLPAPER}).*)
fi

if [ "${FLL_WALLPAPER}" ] && [ ! -f "${XFCE_DESKTOP_XML}" ]; then

	cat > "${XFCE_DESKTOP_XML}" << EOF
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-desktop" version="1.0">
  <property name="backdrop" type="empty">
    <property name="screen0" type="empty">
      <property name="monitor0" type="empty">
        <property name="image-path" type="string" value="${FLL_WALLPAPER}"/>
      </property>
    </property>
  </property>
</channel>
EOF
fi

###
# set panel defaults
###
mkdir -p "${HOME}/.config/xfce4/panel/"
FLL_CONF_PRESEED="${HOME}/.config/xfce4/panel/panels.xml"
if [ ! -f "${FLL_CONF_PRESEED}" ]; then
	cp /usr/share/sidux-settings-xfce/xfce4/panel/panels.xml "${FLL_CONF_PRESEED}"
fi

###
# create .config/autostart dir
###
mkdir -p "${HOME}/.config/autostart"

###
# disable tips on startup
###
FLL_CONF_PRESEED="${HOME}/.config/autostart/xfce4-tips-autostart.desktop"
if grep -s -q '^Hidden=' "${FLL_CONF_PRESEED}"; then
	sed -i 's|^Hidden=.*|Hidden=true|' "${FLL_CONF_PRESEED}"
else
	cat > "${FLL_CONF_PRESEED}" <<EOF

[Desktop Entry]
Hidden=true

EOF
fi

###
# set xfce splash login theme
###
FLL_CONF_PRESEED="${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml"
if [ "${XFCE_SPLASH_THEME}" ]; then
	mkdir -p "${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml"

	if [ ! -f "${FLL_CONF_PRESEED}" ]; then
	        cat > "${FLL_CONF_PRESEED}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
 
<channel name="xfce4-session" version="1.0">
  <property name="splash" type="empty">
    <property name="Engine" type="string" value="${XFCE_SPLASH_ENGINE}"/>
    <property name="engines" type="empty">
      <property name="balou" type="empty">
        <property name="Theme" type="string" value="${XFCE_SPLASH_THEME}"/>
      </property>
    </property>
  </property>
</channel>
EOF
	fi
fi

###
# take care of the trash can
###
mkdir -p "${HOME}/.local/share/Trash/info/" "${HOME}/.local/share/Trash/files/"

###
# scan for index.html in fll specific live mountpoint directories
###
for mntpnt in /fll/*; do
	if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
		INDEXFILE="${mntpnt}/index.html"
		for ext in svg png gif ico; do
			if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
				INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
				break
			fi
		done
		break
	fi
done

###
# create ~/Desktop if not present
###
mkdir -p "${HOME}/Desktop"

###
# create desktop shortcut to index.html
###
if [ -f "${INDEXFILE}"  ] && \
   [ ! -f "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" ]; then
	cat > "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
<<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=x-www-browser ${INDEXFILE}
Icon=${INDEXICON}
Terminal=No
Name=${FLL_CDROM_INDEX}
GenericName=${FLL_CDROM_INDEX}
EOF

	if [ "${NOINTRO}" != "yes" ]; then
		ln -sf "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
			"${HOME}/.config/autostart/"
	fi
elif [ -e "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop" ]; then
	# toram + persistency
	rm -f "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop"
fi
