#!/bin/sh

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

PATH=/sbin:/usr/sbin:$PATH

# set default umask
umask 0022

# this is only invoked from fll-kde-desktop, inherit its environment
NAME="fll-xfce-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
		nointro)
			NOINTRO="yes"
			;;
	esac
done

###
# set wallpaper and desktop defaults in desktop.xml
###
FLL_CONF_PRESEED="${HOME}/.config/xfce4/mcs_settings/desktop.xml"
if [ "${FLL_WALLPAPER}" ]; then
	if [ ! -f "${FLL_CONF_PRESEED}" ]; then
		mkdir -p "${HOME}/.config/xfce4/mcs_settings/"
		cat >"${FLL_CONF_PRESEED}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mcs-option SYSTEM "mcs-option.dtd">

<mcs-option>
	<option name="brightness_0_0" type="int" value="0"/>
	<option name="color1_0_0" type="color" value="		15104,		23296,		35072,		65535"/>
	<option name="color2_0_0" type="color" value="		15872,		26624,		40448,		65535"/>
	<option name="colorstyle_0_0" type="int" value="0"/>
	<option name="desktopiconstyle" type="int" value="2"/>
	<option name="icons_use_system_font_size" type="int" value="1"/>
	<option name="imagepath_0_0" type="string" value="${FLL_WALLPAPER}"/>
	<option name="imagestyle_0_0" type="int" value="3"/>
	<option name="showdm" type="int" value="1"/>
	<option name="showimage_0_0" type="int" value="1"/>
	<option name="showwl" type="int" value="1"/>
</mcs-option>
EOF
	fi
fi

###
# create .config/autostart dir
###
mkdir -p "${HOME}/.config/autostart"

###
# disable tips on startup
###
FLL_CONF_PRESEED="${HOME}/.config/autostart/xfce4-tips-autostart.desktop"
if grep -s '^Hidden=' "${FLL_CONF_PRESEED}"; then
	sed -i 's|^Hidden=.*|Hidden=true|' "${FLL_CONF_PRESEED}"
else
	cat > "${FLL_CONF_PRESEED}" <<EOF

[Desktop Entry]
Hidden=true

EOF
fi

###
# set xfce splash login theme
###
if [ "${XFCE_SPLASH_THEME}" ]; then
	mkdir -p "${HOME}/.config/xfce4-session"

	if [ ! -f "${HOME}/.config/xfce4-session/xfce4-splash.rc" ]; then
	        cat > "${HOME}/.config/xfce4-session/xfce4-splash.rc" << EOF

[Engine: ${XFCE_SPLASH_ENGINE}]
Theme=${XFCE_SPLASH_THEME}

EOF
	fi

	if [ ! -f "${HOME}/.config/xfce4-session/xfce4-session.rc" ]; then
	        cat > "${HOME}/.config/xfce4-session/xfce4-session.rc" << EOF

[Splash Screen]
Theme=${XFCE_SPLASH_THEME}
Engine=${XFCE_SPLASH_ENGINE}

EOF
	fi

fi

###
# take care of the trash can
###
mkdir -p "${HOME}/.local/share/Trash/info/" "${HOME}/.local/share/Trash/files/"

###
# scan for index.html in fll specific live mountpoint directories
###
for mntpnt in /fll/*; do
	if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
		INDEXFILE="${mntpnt}/index.html"
		for ext in svg png gif ico; do
			if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
				INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
				break
			fi
		done
		break
	fi
done

###
# create ~/Desktop if not present
###
mkdir -p "${HOME}/Desktop"

###
# create desktop shortcut to index.html
###
if [ -f "${INDEXFILE}"  ] && \
   [ ! -f "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" ]; then
	cat > "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
<<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=x-www-browser ${INDEXFILE}
Icon=${INDEXICON}
Terminal=No
Name=${FLL_CDROM_INDEX}
GenericName=${FLL_CDROM_INDEX}
EOF

	if [ "${NOINTRO}" != "yes" ]; then
		ln -sf "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
			"${HOME}/.config/autostart/"
	fi
elif [ -e "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop" ]; then
	# toram + persistency
	rm -f "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop"
fi
