#!/bin/dash

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 F.U.L.L.S.T.O.R.Y Project
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

# set default umask
umask 0022

# this is only invoked from fll-kde-desktop, inherit its environment
NAME="fll-xfce-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
## functions
###
. /usr/share/desktop-defaults-common/fll-desktop-func

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
		nointro)
			NOINTRO="yes"
			;;
	esac
done

##########
# main() #
##########
cp_desktop_defaults_from /usr/share/desktop-defaults-xfce

###
# force wallpaper, desktop.xml is provided by our dot.config
###
FLL_CONF_PRESEED="${HOME}/.config/xfce4/mcs_settings/desktop.xml"
if [ "${FLL_WALLPAPER}" ] && [ -f "${FLL_CONF_PRESEED}" ]; then
	if grep -s -q 'imagepath' "${FLL_CONF_PRESEED}"; then
		sed -i '/imagepath/s|\(.*value="\)[^"]\+\(".*\)|\1'"$FLL_WALLPAPER"'\2|' \
			"${FLL_CONF_PRESEED}"
	fi
fi

###
# create .config/autostart dir
###
mkdir -p "${HOME}/.config/autostart"

###
# disable tips on startup
###
FLL_CONF_PRESEED="${HOME}/.config/autostart/xfce4-tips-autostart.desktop"
touch "${FLL_CONF_PRESEED}"
if grep -q '^Hidden=' "${FLL_CONF_PRESEED}"; then
	sed -i 's|^Hidden=.*|Hidden=true|' "${FLL_CONF_PRESEED}"
else
	cat > "${FLL_CONF_PRESEED}" \
<<EOF
[Desktop Entry]
Hidden=true

EOF
fi

###
# set xfce splash login theme
# XXX: TODO
###

###
# Add battmon plugin to panel
###
for bat in /proc/acpi/battery/*/info; do 
	if [ -f "$bat" ]; then 
		sed -i  -e "/<item name=\"battmon\"/d" \
			-e "s|^\([ \t]*\)\(<item[ \t]*name\=\"systray\".*\)|\1<item name=\"battmon\" id=\"11927411720\"\/\>\n\1\2|" \
			"${HOME}/.config/xfce4/panel/panels.xml"
		break
	fi
done

###
# Start mixer
###
if [ -x /usr/bin/xfce4-mixer ]; then
	# sound system active?
	if grep -q "^snd" /proc/modules; then
		if [ -f "${HOME}/.config/xfce4/panel/panels.xml" ]; then
			sed -i  -e "/<item name=\"xfce4-mixer\"/d" \
				-e "s|^\([ \t]*\)\(<item[ \t]*name\=\"systray\".*\)|\1<item name=\"xfce4-mixer\" id=\"11927313170\"\/\>\n\1\2|" \
				"${HOME}/.config/xfce4/panel/panels.xml"
		fi
	fi
fi


###
# take care of the trash can
###
mkdir -p	"${HOME}/.local/share/Trash/info" \
		"${HOME}/.local/share/Trash/files/"

###
# scan for index.html in fll specific live mountpoint directories
###
for mntpnt in /fll/*; do
	if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
		INDEXFILE="${mntpnt}/index.html"
		for ext in svg png gif ico; do
			if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
				INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
				break
			fi
		done
		break
	fi
done

###
# create ~/Desktop if not present
###
mkdir -p "${HOME}/Desktop"

###
# create desktop shortcut to index.html
###
if [ -f "${INDEXFILE}"  ] && [ ! -f "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" ]; then
	cat > "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
<<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=x-www-browser ${INDEXFILE}
Icon=${INDEXICON}
Terminal=No
Name=${FLL_CDROM_INDEX}
GenericName=${FLL_CDROM_INDEX}
EOF

	if [ "${NOINTRO}" != "yes" ]; then
		ln -sf "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
			"${HOME}/.config/autostart/"
	fi
elif [ -e "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop" ]; then
	# toram + persistency
	rm -f "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop"
fi
