# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("ui.allow_platform_file_picker", false);
user_pref("layout.css.dpi", 0);
user_pref("font.minimum-size.x-western", 12);
user_pref("font.name.sans-serif.x-western", "Bitstream Vera Serif");
user_pref("font.name.serif.x-western", "Bitstream Vera Sans");