#!/bin/dash

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 F.U.L.L.S.T.O.R.Y Project
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2007-2008 Andreas Weber <andreas@it-weber.com>
# Copyright: (C) 2007-2008 Horst Tritremmel <hjt@sidux.com>
# Copyright: (C) 2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

# set default umask
umask 0022

# this is only invoked from fll-kde-desktop, inherit its environment
NAME="fll-gnome-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
## functions
###
. /usr/share/desktop-defaults-common/fll-desktop-func

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
		nointro)
			NOINTRO="yes"
			;;
	esac
done

##########
# main() #
##########
cp_desktop_defaults_from /usr/share/desktop-defaults-gnome

for mntpnt in /fll/*; do
	if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
		INDEXFILE="${mntpnt}/index.html"
		for ext in svg png gif ico; do
			if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
				INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
				break
			fi
		done
		break
	fi
done

###
# create desktop icon . . .
###
if [ ! -d "${HOME}/.config/autostart" ]; then
	mkdir -p "${HOME}/.config/autostart"
fi

if [ -f "${INDEXFILE}"  ] && [ "${NOINTRO}" != "yes" ] && \
	[ ! -f "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop" ]; then
	cat > "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop" \
<<EOF
[Desktop Entry]
Name=${FLL_DISTRO_NAME}-manual
Encoding=UTF-8
Version=1.0
Name[de_DE]=${FLL_DISTRO_NAME}-manual
Exec=epiphany file:${INDEXFILE}
X-GNOME-Autostart-enabled=true
EOF
fi

###
# create ~/Desktop if not present
###
if [ ! -d "${HOME}/Desktop" ]; then
	mkdir -p "${HOME}/Desktop"
fi

if [ -f "${INDEXFILE}" ]; then
	cat > "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
<<EOF
[Desktop Entry]
Name=${FLL_CDROM_INDEX}
Exec=epiphany file:${INDEXFILE}
Type=Application
Icon=${INDEXICON}
Terminal=0
EOF
fi

# background
gconftool-2 --set "/desktop/gnome/background/picture_options" --type string "stretched"
gconftool-2 --set "/desktop/gnome/background/picture_filename" --type string "${FLL_WALLPAPER}"

# theme
[ -d "/usr/share/themes/Clearlooks" ] && gconftool-2 --set "/desktop/gnome/interface/gtk_theme" --type string "Clearlooks"

# panels
gconftool-2 --set "/apps/panel/toplevels/bottom_panel_screen0/background/opacity" --type int 30000
gconftool-2 --set "/apps/panel/toplevels/top_panel_screen0/background/opacity" --type int 30000
gconftool-2 --set "/apps/panel/toplevels/bottom_panel_screen0/background/type" --type string "color"
gconftool-2 --set "/apps/panel/toplevels/top_panel_screen0/background/type" --type string "color"

# osd
gconftool-2 --set "/apps/gnome-osd/avoid_panels" --type bool true
gconftool-2 --set "/apps/gnome-osd/animations" --type bool true
gconftool-2 --set "/apps/gnome-osd/drop_shadow" --type bool true
gconftool-2 --set "/apps/gnome-osd/osd_halignment" --type string "center"
gconftool-2 --set "/apps/gnome-osd/osd_vposition" --type string "top"
gconftool-2 --set "/apps/gnome-osd/plugins/gaim/enabled" --type bool true

# sound
gconftool-2 --set "/desktop/gnome/sound/enable_esd" --type bool true
gconftool-2 --set "/desktop/gnome/sound/event_sounds" --type bool true

# screensaver
gconftool-2 --set "/apps/gnome-screensaver/lock_enabled" --type bool false

# terminal
gconftool-2 --set "/apps/gnome-terminal/profiles/Default/background_color" --type string '#FFFFFF'

# nautilus
gconftool-2 --set "/apps/nautilus/preferences/always_use_browser" --type bool true
gconftool-2 --set "/apps/nautilus/icon_view/default_zoom_level" --type string "small"

# epiphany
gconftool-2 --set "/apps/epiphany/general/homepage" --type string "http://www.sidux.com"

# set prefs for epiphany so the right offline-manual page shows
LANG_CODE=${LANGUAGE%%[-_]*}

if [ ! -d "${HOME}/.gnome2/epiphany/mozilla/epiphany" ]; then
	mkdir -p ${HOME}/.gnome2/epiphany/mozilla/epiphany 
fi
cat > "${HOME}/.gnome2/epiphany/mozilla/epiphany/prefs.js" \
<< EOF
user_pref("general.useragent.locale", "${LANG_CODE}");  
EOF

