#!/bin/dash

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 F.U.L.L.S.T.O.R.Y Project
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

set -e

# set default umask
umask 0022

# this is only invoked from fll-common-desktop, inherit its environment
NAME="fll-common-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
## functions
###
. /usr/share/desktop-defaults-common/fll-desktop-func

cp_desktop_defaults_from /usr/share/desktop-defaults-common

###
# emulate firefox^iceweasel security via obscurity 
###
if [ -f "${HOME}/.mozilla/firefox/profiles.ini" ]; then
	MOZPROFILE=$(awk '
		/^\[Profile/ {
			if (/Profile0/)
				inprof=1
			else
				inprof=0
		}
		/^Path=/ {
			if (inprof) {
				sub("Path=", "", $0)
				print
			}
		}' "${HOME}/.mozilla/firefox/profiles.ini")
fi

if [ "${MOZPROFILE}" = "XXXX.default" ] && \
	[ -d "${HOME}/.mozilla/firefox/${MOZPROFILE}" ]; then
	# use mawk: rand() behaviour is different among awk variants
	NEWMOZPROFILE=$(mawk '
		BEGIN{
			printf("%d.%s\n", int(10000000 * rand()), "default")
	}')

	mv "${HOME}/.mozilla/firefox/${MOZPROFILE}" \
		"${HOME}/.mozilla/firefox/${NEWMOZPROFILE}"
	sed -i 's|^Path='"${MOZPROFILE}"'|Path='"${NEWMOZPROFILE}"'|' \
		"${HOME}/.mozilla/firefox/profiles.ini"
fi

###
# make iceweasel default browser if installed
###
ICEWEASEL=$(which iceweasel 2>/dev/null)
if [ -x "${ICEWEASEL}" ]; then
	update-alternatives --set x-www-browser "${ICEWEASEL}" >/dev/null
fi

###
# su-to-root -> sudo
###
if [ "$(which su-to-root 2>/dev/null)" ]; then
	touch "${HOME}/.su-to-rootrc"
	if grep -q '^SU_TO_ROOT_SU=' "${HOME}/.su-to-rootrc"; then
		sed -i 's|^SU_TO_ROOT_SU=.*|SU_TO_ROOT_SU=sudo|' \
			"${HOME}/.su-to-rootrc"
	else
		echo 'SU_TO_ROOT_SU=sudo' >> "${HOME}/.su-to-rootrc"
	fi
	chown "${FLL_LIVE_USER}:${FLL_LIVE_USER}" "${HOME}/.su-to-rootrc"
fi

###
# gksu -> sudo
###
if [ "$(which gconftool-2 2>/dev/null)" ]; then
	sudo -u "${FLL_LIVE_USER}" \
		gconftool-2 -s -t bool /apps/gksu/sudo-mode true
	sudo -u "${FLL_LIVE_USER}" \
		gconftool-2 -s -t bool /apps/gksu/display-no-pass-info false
fi

###
# kdesu -> sudo
###
if [ "$(which kdesu 2>/dev/null)" ]; then
	if [ ! -d "${HOME}/.kde/share/config" ]; then
		install --directory --group="${FLL_LIVE_USER}" --owner="${FLL_LIVE_USER}" \
			"${HOME}/.kde/share/config"
	fi

	touch "${HOME}/.kde/share/config/kdesurc"
	if grep -q '^super-user-command=' "${HOME}/.kde/share/config/kdesurc"; then
		sed -i 's|^super-user-command=.*|super-user-command=sudo|' \
			"${HOME}/.kde/share/config/kdesurc"
	else
		cat > "${HOME}/.kde/share/config/kdesurc" \
<<EOF
[super-user-command]
super-user-command=sudo
EOF
	fi
	chown "${FLL_LIVE_USER}:${FLL_LIVE_USER}" \
		"${HOME}/.kde/share/config/kdesurc"
fi
