#!/bin/sh

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008-2013 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# Copyright: (C) 2013 Roland Engert <Roland.Engert@web.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

PATH=/sbin:/usr/sbin:$PATH

# set default umask
umask 0022

# this is only invoked from fll-razorqt-desktop, inherit its environment
NAME="fll-razorqt-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
		nointro)
			NOINTRO="yes"
			;;
	esac
done

###
# set wallpaper defaults in desktop.conf
###
mkdir -p "${HOME}/.config/razor"
DESKTOP_CONF="${HOME}/.config/razor/desktop.conf"

# handle case where FLL_WALLPAPER is defined in kde4 directory syntax
# aptosid-art-wallpaper-* provides a symlink in /usr/share/wallpapers/ to common res wallpaper
if [ -d ${FLL_WALLPAPER} ]; then
	FLL_WALLPAPER=$(find $(dirname ${FLL_WALLPAPER}) -maxdepth 1 -type l -iname $(basename ${FLL_WALLPAPER}).*)
fi

if [ "${FLL_WALLPAPER}" ] && [ ! -f "${DESKTOP_CONF}" ]; then

	cat > "${DESKTOP_CONF}" << EOF
[razor]
screens\size=1
screens\1\desktops\1\wallpaper_type=pixmap
screens\1\desktops\1\wallpaper=/usr/share/wallpapers/${FLL_WALLPAPER}-wide.png
screens\1\desktops\1\keep_aspect_ratio=false
screens\1\desktops\1\size=1
EOF
fi

###
# create .config/autostart dir
###
mkdir -p "${HOME}/.config/autostart"

###
# take care of the trash can
###
#mkdir -p "${HOME}/.local/share/Trash/info/" "${HOME}/.local/share/Trash/files/"

###
# scan for index.html in fll specific live mountpoint directories
###
for mntpnt in /fll/*; do
	if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
		INDEXFILE="${mntpnt}/index.html"
		for ext in svg png gif ico; do
			if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
				INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
				break
			fi
		done
		break
	fi
done

###
# create ~/Desktop if not present
###
mkdir -p "${HOME}/Desktop"

###
# create desktop shortcut to index.html
###

if [ -f "${INDEXFILE}"  ] && \
   [ ! -f "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" ]; then
	cat > "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
<<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=x-www-browser ${INDEXFILE}
Icon=${INDEXICON}
Terminal=No
Name=${FLL_CDROM_INDEX}
GenericName=${FLL_CDROM_INDEX}
EOF

	if [ "${NOINTRO}" != "yes" ]; then
		ln -sf "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
			"${HOME}/.config/autostart/"
	fi
elif [ -e "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop" ]; then
	# toram + persistency
	rm -f "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop"
fi
