#!/bin/sh

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008-2016 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# Copyright: (C) 2013 Roland Engert <Roland.Engert@web.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# https://github.com/fullstory
###

PATH=/sbin:/usr/sbin:$PATH

# set default umask
umask 0022

# this is only invoked from fll-razorqt-desktop, inherit its environment
NAME="fll-razorqt-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
	esac
done

###
# set wallpaper defaults in desktop.conf
###
mkdir -p "${HOME}/.config/razor"
DESKTOP_CONF="${HOME}/.config/razor/desktop.conf"

# handle case where FLL_WALLPAPER is defined in kde4 directory syntax
# aptosid-art-wallpaper-* provides a symlink in /usr/share/wallpapers/ to common res wallpaper
if [ -d ${FLL_WALLPAPER} ]; then
	FLL_WALLPAPER=$(find $(dirname ${FLL_WALLPAPER}) -maxdepth 1 -type l -iname $(basename ${FLL_WALLPAPER}).*)
fi

if [ "${FLL_WALLPAPER}" ] && [ ! -f "${DESKTOP_CONF}" ]; then
	cat > "${DESKTOP_CONF}" << EOF
[razor]
screens\size=1
screens\1\desktops\1\wallpaper_type=pixmap
screens\1\desktops\1\wallpaper=${FLL_WALLPAPER}
screens\1\desktops\1\keep_aspect_ratio=false
screens\1\desktops\1\size=1
EOF
fi

###
# create .config/autostart dir
###
mkdir -p "${HOME}/.config/autostart"

###
# take care of the trash can
###
#mkdir -p "${HOME}/.local/share/Trash/info/" "${HOME}/.local/share/Trash/files/"

###
# create ~/Desktop if not present
###
mkdir -p "${HOME}/Desktop"
